### ISSUE TITLE
picke error with Django 3

### ISSUE THREAD

**Issue by jimmy927** [bitranox/wrapt_timeout_decorator#21]
* **I'm submitting a ... **
  - [x] bug report
  - [ ] feature request
  - [ ] support request

* **Please tell us about your environment:**

It works with the normal timeout_decorator on Linux and Mac OS, but i am trying to run it on windows for development.

It is a django (3.0.7) management command, i think that might be the issue ?
Any ideas how i can avoid this ?

Would be really great if i don't have to rip out the decorator entirely, it is very useful and elegant at the current point in time.

- Version of wrapt_timeout_decorator : 

1.3.1

- Python Version : 

3.7

- OS, OS Version : 

Windows 10

* **Other information** (e.g. detailed explanation, stack traces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow
, gitter, etc)

```
Traceback (most recent call last):
  File "C:\Users\jimmy\venv\odi2\lib\site-packages\multiprocess\spawn.py", line 115, in _main
    self = reduction.pickle.load(from_parent)
  File "C:\Users\jimmy\venv\odi2\lib\site-packages\dill\_dill.py", line 270, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
  File "C:\Users\jimmy\venv\odi2\lib\site-packages\dill\_dill.py", line 473, in load
    obj = StockUnpickler.load(self)
  File "C:\Users\jimmy\venv\odi2\lib\site-packages\dill\_dill.py", line 463, in find_class
    return StockUnpickler.find_class(self, module, name)
  File "C:\Users\jimmy\PycharmProjects\odi\core\driver_utils.py", line 13, in <module>
    from core.models import OdiSession
  File "C:\Users\jimmy\PycharmProjects\odi\core\models.py", line 8, in <module>
    from django.contrib.auth.models import User
  File "C:\Users\jimmy\venv\odi2\lib\site-packages\django\contrib\auth\models.py", line 2, in <module>
    from django.contrib.auth.base_user import AbstractBaseUser, BaseUserManager
  File "C:\Users\jimmy\venv\odi2\lib\site-packages\django\contrib\auth\base_user.py", line 47, in <module>
    class AbstractBaseUser(models.Model):
  File "C:\Users\jimmy\venv\odi2\lib\site-packages\django\db\models\base.py", line 107, in __new__
    app_config = apps.get_containing_app_config(module)
  File "C:\Users\jimmy\venv\odi2\lib\site-packages\django\apps\registry.py", line 252, in get_containing_app_config
    self.check_apps_ready()
  File "C:\Users\jimmy\venv\odi2\lib\site-packages\django\apps\registry.py", line 135, in check_apps_ready
    raise AppRegistryNotReady("Apps aren't loaded yet.")
django.core.exceptions.AppRegistryNotReady: Apps aren't loaded yet.
Traceback (most recent call last):
  File "C:\Users\jimmy\venv\odi2\lib\site-packages\multiprocess\popen_spawn_win32.py", line 89, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\jimmy\venv\odi2\lib\site-packages\multiprocess\reduction.py", line 63, in dump
    ForkingPickler(file, protocol, *args, **kwds).dump(obj)
  File "C:\Users\jimmy\venv\odi2\lib\site-packages\dill\_dill.py", line 446, in dump
    StockPickler.dump(self, obj)
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 437, in dump
    self.save(obj)
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 662, in save_reduce
    save(state)
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\jimmy\venv\odi2\lib\site-packages\dill\_dill.py", line 933, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 885, in _batch_setitems
    save(v)
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 774, in save_tuple
    save(element)
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 662, in save_reduce
    save(state)
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\jimmy\venv\odi2\lib\site-packages\dill\_dill.py", line 933, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 885, in _batch_setitems
    save(v)
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 774, in save_tuple
    save(element)
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 662, in save_reduce
    save(state)
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\jimmy\venv\odi2\lib\site-packages\dill\_dill.py", line 933, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 885, in _batch_setitems
    save(v)
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 549, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 662, in save_reduce
    save(state)
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\jimmy\venv\odi2\lib\site-packages\dill\_dill.py", line 933, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 885, in _batch_setitems
    save(v)
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\jimmy\venv\odi2\lib\site-packages\dill\_dill.py", line 933, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 859, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 885, in _batch_setitems
    save(v)
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 774, in save_tuple
    save(element)
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 504, in save
    f(self, obj) # Call unbound method with explicit self
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 749, in save_str
    self.write(BINUNICODE + pack("<I", n) + encoded)
  File "C:\Users\jimmy\AppData\Local\Programs\Python\Python37\lib\pickle.py", line 229, in write
    return self.file_write(data)
BrokenPipeError: [Errno 32] Broken pipe

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\jimmy\venv\odi2\lib\site-packages\django\core\management\base.py", line 328, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\jimmy\venv\odi2\lib\site-packages\django\core\management\base.py", line 369, in execute
    output = self.handle(*args, **options)
  File "C:\Users\jimmy\PycharmProjects\odi\core\management\commands\conversation_gatherer.py", line 14, in handle
    core.conversation_gatherer.start()
  File "C:\Users\jimmy\PycharmProjects\odi\core\conversation_gatherer.py", line 39, in start
    init_sessions_and_get_conversations()
  File "C:\Users\jimmy\PycharmProjects\odi\core\conversation_gatherer.py", line 68, in init_sessions_and_get_conversations
    odi_sess, odi_session_model = init(u, 1920, 1080)
  File "C:\Users\jimmy\PycharmProjects\odi\core\situation_solver.py", line 564, in init
    check_linkedin_performance(driver)
  File "C:\Users\jimmy\venv\odi2\lib\site-packages\wrapt\wrappers.py", line 567, in __call__
    args, kwargs)
  File "C:\Users\jimmy\venv\odi2\lib\site-packages\wrapt_timeout_decorator\wrapt_timeout_decorator.py", line 123, in wrapper
    return wrapped_with_timeout(wrap_helper)
  File "C:\Users\jimmy\venv\odi2\lib\site-packages\wrapt_timeout_decorator\wrapt_timeout_decorator.py", line 131, in wrapped_with_timeout
    return wrapped_with_timeout_process(wrap_helper)
  File "C:\Users\jimmy\venv\odi2\lib\site-packages\wrapt_timeout_decorator\wrapt_timeout_decorator.py", line 145, in wrapped_with_timeout_process
    return timeout_wrapper()
  File "C:\Users\jimmy\venv\odi2\lib\site-packages\wrapt_timeout_decorator\wrap_function_multiprocess.py", line 37, in __call__
    self.__process.start()
  File "C:\Users\jimmy\venv\odi2\lib\site-packages\multiprocess\process.py", line 112, in start
    self._popen = self._Popen(self)
  File "C:\Users\jimmy\venv\odi2\lib\site-packages\multiprocess\context.py", line 223, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
  File "C:\Users\jimmy\venv\odi2\lib\site-packages\multiprocess\context.py", line 322, in _Popen
    return Popen(process_obj)
  File "C:\Users\jimmy\venv\odi2\lib\site-packages\multiprocess\popen_spawn_win32.py", line 91, in __init__
    set_spawning_popen(None)
OSError: [Errno 22] Invalid argument
Waiting up to 5 seconds.
Sent all pending logs.

Process finished with exit code 1

```

**Comment by bitranox** [comment]
Dear Jimmy,
what I can see from the stacktrace, the decorated function/class can not be pickled - therefore You cant use it on windows with multiprocessing.

Try to narrow down the scope of the timeout decorator - or make Your function/class pickable !

yours sincerely
Robert
