### ISSUE TITLE
Replacing pathlib dependency with importlib_metadata

### ISSUE THREAD

**Issue by Arjunsankarlal** [bitranox/wrapt_timeout_decorator#26]
This is kind of related to this [issue](https://github.com/Kozea/WeasyPrint/issues/807).

The problem is while using pathlib as a dependency in linux CentOS is overriding the current lib. And hence this breaks few other libraries functionalities. I my case [spacy](https://github.com/explosion/spaCy) - where while importing the package, it causes the following error,

```
Traceback (most recent call last):
  File "/Users/arjun/environments/test3.6/lib/python3.6/site-packages/catalogue.py", line 8, in <module>
    import importlib.metadata as importlib_metadata
ModuleNotFoundError: No module named 'importlib.metadata'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/arjun/environments/test3.6/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/Users/arjun/environments/test3.6/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/home/Users/arjun/nlpparser/__init__.py", line 1, in <module>
    import spacy
  File "/Users/arjun/environments/test3.6/lib/python3.6/site-packages/spacy/__init__.py", line 10, in <module>
    from thinc.neural.util import prefer_gpu, require_gpu
  File "/Users/arjun/environments/test3.6/lib/python3.6/site-packages/thinc/__init__.py", line 8, in <module>
    from ._registry import registry
  File "/Users/arjun/environments/test3.6/lib/python3.6/site-packages/thinc/_registry.py", line 1, in <module>
    import catalogue
  File "/Users/arjun/environments/test3.6/lib/python3.6/site-packages/catalogue.py", line 10, in <module>
    import importlib_metadata
  File "/Users/arjun/environments/test3.6/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 623, in <module>
    __version__ = version(__name__)
  File "/Users/arjun/environments/test3.6/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 585, in version
    return distribution(distribution_name).version
  File "/Users/arjun/environments/test3.6/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 285, in version
    return self.metadata['Version']
  File "/Users/arjun/environments/test3.6/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 273, in metadata
    self.read_text('METADATA')
  File "/Users/arjun/environments/test3.6/lib/python3.6/site-packages/importlib_metadata/__init__.py", line 545, in read_text
    return self._path.joinpath(filename).read_text(encoding='utf-8')
AttributeError: 'PosixPath' object has no attribute 'read_text'
```

And after I uninstalled `pathlib` and replaced `importlib_metadata` in `__init__.py` as

```
import importlib_metadata
with open(str(importlib_metadata.pathlib.Path(__file__).parent / 'version.txt'), mode='r') as version_file:
```

instead of 

```
import pathlib
with open(str(pathlib.Path(__file__).parent / 'version.txt'), mode='r') as version_file:
```

works properly without breaking anything. And I didn't face this issue in MacOS but only in linux.

**Comment by bitranox** [comment]
IC - ok - i will make a new release in the next weeks, which does not use pathlib in the `__init__.py ` - lets look if that solves the problem in the future.
Your help on that would be appreciated, and thanks for the information !

**Comment by Arjunsankarlal** [comment]
Cool then 👍

**Comment by direbutterfly** [comment]
Any update on this bug? Still running into the same bug!

**Comment by bitranox** [comment]
sorry - too busy atm - will come in the next weeks ...

**Comment by Moon-developer** [comment]
PS: still an issue to this day.

**Comment by bitranox** [comment]
@Moon-developer
@direbutterfly
@Arjunsankarlal

thank You for Your effort reporting that issue.
Did You check Yourself that this really is still an issue ? 
I almost can not believe that ```pathlib``` should not work correctly on Centos.

What also makes me suspicious is the claim : 

```And after I uninstalled pathlib and replaced importlib_metadata in __init__.py as ... ```

I am not aware that You can uninstall parts of the standard libraries ? 

please be so kind and let me know - because I have 50+ repositories, and if that is really the case with centos, I would consider to change that on all my repos.

so please try : 

```
python --version
python -m pip install --upgrade pip
python -m pip install git+https://github.com/bitranox/wrapt_timeout_decorator.git
```
and let me know the detailed results ... 

thanks for Your cooperation

yours sincerely

bitranox

**Comment by bitranox** [comment]
check the newest release - it should be solved.
https://github.com/bitranox/wrapt_timeout_decorator/releases/tag/v1.3.2
