### ISSUE TITLE
Doesn't work

### ISSUE THREAD

**Issue by vadimszzz** [bitranox/wrapt_timeout_decorator#39]
```
Exception ignored in: <function _after_fork at 0x103999dc0>
Traceback (most recent call last):
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/threading.py", line 1486, in _after_fork
    thread._reset_internal_locks(True)
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/threading.py", line 829, in _reset_internal_locks
    self._tstate_lock._at_fork_reinit()
AttributeError: 'NoneType' object has no attribute '_at_fork_reinit'
Traceback (most recent call last):
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/Users/x/Downloads/Projects/ios-apps-research-2022/exynex/__main__.py", line 83, in <module>
    cli()
  File "/Users/x/Downloads/Projects/ios-apps-research-2022/exynex/__main__.py", line 53, in cli
    cli_commands()
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/site-packages/click/core.py", line 1137, in __call__
    return self.main(*args, **kwargs)
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/site-packages/click/core.py", line 1062, in main
    rv = self.invoke(ctx)
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/site-packages/click/core.py", line 1668, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/site-packages/click/core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/site-packages/click/core.py", line 763, in invoke
    return __callback(*args, **kwargs)
  File "/Users/x/Downloads/Projects/ios-apps-research-2022/exynex/cli/package.py", line 64, in dump
    package_util.dump_fouldecrypt(**kwargs)
  File "/Users/x/Downloads/Projects/ios-apps-research-2022/exynex/package.py", line 16, in dump_fouldecrypt
    tmp_dir = shell.exec(frida_device, "mktemp -d", verbose=verbose).stdout.decode("utf-8").strip("\n")
  File "/Users/x/Downloads/Projects/ios-apps-research-2022/exynex/shell.py", line 158, in exec
    exit_code = _exec_with_exit_code(frida_device, cmd, [_stdout, stdout], [_stderr, stderr])
  File "/Users/x/Downloads/Projects/ios-apps-research-2022/exynex/shell.py", line 130, in _exec_with_exit_code
    while frida_utils.process_is_running(frida_device, pid):
  File "/Users/x/Downloads/Projects/ios-apps-research-2022/exynex/utils.py", line 76, in wrapper
    return func(*args, **kwargs)
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/site-packages/wrapt_timeout_decorator/wrapt_timeout_decorator.py", line 139, in wrapper
    return wrapped_with_timeout(wrap_helper)
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/site-packages/wrapt_timeout_decorator/wrapt_timeout_decorator.py", line 148, in wrapped_with_timeout
    return wrapped_with_timeout_process(wrap_helper)
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/site-packages/wrapt_timeout_decorator/wrapt_timeout_decorator.py", line 162, in wrapped_with_timeout_process
    return timeout_wrapper()
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/site-packages/wrapt_timeout_decorator/wrap_function_multiprocess.py", line 47, in __call__
    self.cancel()
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/site-packages/wrapt_timeout_decorator/wrap_function_multiprocess.py", line 55, in cancel
    raise_exception(self.wrap_helper.timeout_exception, self.wrap_helper.exception_message)
  File "/Users/x/.pyenv/versions/3.9.0/lib/python3.9/site-packages/wrapt_timeout_decorator/wrap_helper.py", line 181, in raise_exception
    raise exception(exception_message)
TimeoutError: Function process_is_running timed out after 20.0 seconds
```

**Comment by bitranox** [comment]
what do You mean "it does not work" ? 
the function "process_is_running" timed out after 20 seconds - so the decorator throwed a TimeoutError
If You think this is not correct, please provide a minimal code example.

Yours sincerely
Bitranox

**Comment by bitranox** [comment]
closed due to inactivity and no further information provided

**Comment by vadimszzz** [comment]
You asshole.
Project doesn't work

**Comment by bitranox** [comment]
Dear Vadim, 
Thanks for Your nice message before You edited it - always happy to help!
Additionaly I would suggest to read the extensive manual, and/or provide a brief code example.
You should check out the [``ISSUE_TEMPLATE.md``](https://github.com/bitranox/wrapt_timeout_decorator/blob/master/ISSUE_TEMPLATE.md) for the information we usually need in order to analyze whats going on.
I am afraid we can not help only from a traceback.
Finally I would ask You to read the [``CODE_OF_CONDUCT``](https://github.com/bitranox/wrapt_timeout_decorator/blob/master/CODE_OF_CONDUCT.md) before You call me names.
yours sincerely
bitranox, Vienna, Austria
