### ISSUE TITLE
Listed example not working on Windows (Python 3.11)

### ISSUE THREAD

**Issue by ImportTaste** [bitranox/wrapt_timeout_decorator#45]
Windows 10 22H2 (19045.2604)
Python 3.11.2

<details><summary>pip output of installed modules</summary>

```text
Requirement already satisfied: colorama in c:\users\######\appdata\roaming\python\python311\site-packages (from click->cli-exit-tools->wrapt_timeout_decorator) (0.4.6)
Installing collected packages: wrapt, dill, multiprocess, lib-detect-testenv, cli-exit-tools, wrapt_timeout_decorator
Successfully installed cli-exit-tools-1.2.3.2 dill-0.3.4 lib-detect-testenv-2.0.3 multiprocess-0.70.12.2 wrapt-1.15.0 wrapt_timeout_decorator-1.3.12.2
```
</details>

---

I am using the following example from README.rst, the filenames and code are all identical with no alterations:

<details><summary>Code/files used from README.rst</summary>

```python
# lib_test.py:

from wrapt_timeout_decorator import *
from time import sleep
from conf_my_program import conf_my_program

# use_signals = False is not really necessary here, it is set automatically under Windows
# but You can force NOT to use Signals under Linux
@timeout(5, use_signals=False)
def mytest():
    print("Start ", conf_my_program.name)
    for i in range(1,10):
        sleep(1)
        print("{} seconds have passed".format(i))
    return i
```
```python
# conf_my_program.py:

class ConfMyProgram(object):
    def __init__(self):
        self.name:str = 'my_var_name'

conf_my_program = ConfMyProgram()
```
```python
# lib_test.py:

from wrapt_timeout_decorator import *
from time import sleep
from conf_my_program import conf_my_program

# use_signals = False is not really necessary here, it is set automatically under Windows
# but You can force NOT to use Signals under Linux
@timeout(5, use_signals=False)
def mytest():
    print("Start ", conf_my_program.name)
    for i in range(1,10):
        sleep(1)
        print("{} seconds have passed".format(i))
    return i
```
</details>

-----

Here is my attempt to run the code:

> `python.exe my_main.program.py`
```text
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Users\######\AppData\Roaming\Python\Python311\site-packages\multiprocess\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\######\AppData\Roaming\Python\Python311\site-packages\multiprocess\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\######\AppData\Roaming\Python\Python311\site-packages\dill\_dill.py", line 313, in load
    return Unpickler(file, ignore=ignore, **kwds).load()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\######\AppData\Roaming\Python\Python311\site-packages\dill\_dill.py", line 525, in load
    obj = StockUnpickler.load(self)
          ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\######\AppData\Roaming\Python\Python311\site-packages\dill\_dill.py", line 659, in _create_code
    if len(args) == 16: return CodeType(*args)
                               ^^^^^^^^^^^^^^^
TypeError: code() argument 13 must be str, not int
```

**Comment by bitranox** [comment]
ok, will look into - will take a while !

**Comment by bitranox** [comment]
Hello @ImportTaste,
I tried with python 3.10 and 3.11.4 and it works fine.
Maybe You have installed `dill-0.3.5`  or `dill-0.3.5.1`  - there was a problem with that dill versions.
If You install `wrapt_timeout_decorator` now, it will install `dill-0.3.6` which can work fine.
```
c:\users\bitranox\test> python -m pip install --upgrade wrapt_timeout_decorator
c:\users\bitranox\test> dir
14.07.2023  20:41               156      conf_my_program.py
14.07.2023  20:40               471      lib_test.py
14.07.2023  20:45               122      my_program_main.py

c:\users\bitranox\test> python  ./my_program_main.py

Start  my_var_name
1 seconds have passed
2 seconds have passed
3 seconds have passed
4 seconds have passed
Traceback (most recent call last):
    ...
TimeoutError: Function mytest timed out after 5.0 seconds


```

so - it works perfectly fine !

yours sincerely
bitranox
