### ISSUE TITLE
requests.exceptions.ConnectionError: ('Connection aborted.', LineTooLong('got more than 65536 bytes when reading got more than 65536 bytes when reading status line'))

### ISSUE THREAD

**Issue by Joeyteatea** [bitranox/wrapt_timeout_decorator#46]
running cases by python command, and will occur this error after running cases for 2 or more times.

Traceback (most recent call last):
  File "/Users/joey/Desktop/05-Project/applib/main.py", line 12, in <module>
    main(project_root)
  File "/Users/joey/Desktop/05-Project/applib/applib/__main__.py", line 103, in main
    run_script()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/wrapt_timeout_decorator/wrapt_timeout_decorator.py", line 146, in wrapper
    return wrapped_with_timeout(wrap_helper)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/wrapt_timeout_decorator/wrapt_timeout_decorator.py", line 155, in wrapped_with_timeout
    return wrapped_with_timeout_process(wrap_helper)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/wrapt_timeout_decorator/wrapt_timeout_decorator.py", line 169, in wrapped_with_timeout_process
    return timeout_wrapper()
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/wrapt_timeout_decorator/wrap_function_multiprocess.py", line 60, in __call__
    return self.value
/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/multiprocessing/resource_tracker.py:219: UserWarning: resource_tracker: There appear to be 8 leaked semaphore objects to clean up at shutdown
  warnings.warn('resource_tracker: There appear to be %d '
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/wrapt_timeout_decorator/wrap_function_multiprocess.py", line 135, in value
    raise result
requests.exceptions.ConnectionError: ('Connection aborted.', LineTooLong('got more than 65536 bytes when reading got more than 65536 bytes when reading status line'))

**Comment by bitranox** [comment]
can You share a minimal example to provoke that error ?
