### ISSUE TITLE
Error when running on windows

### ISSUE THREAD

**Issue by fgvieira** [bitranox/wrapt_timeout_decorator#58]
* **I'm submitting a ...**
  - [ ] bug report
  - [ ] feature request
  - [x] support request

While running on windows (as a GitHub action) I get the error:
```
  File "D:\a\snakemake\snakemake\tests\common.py", line 377, in run
    dag_api.execute_workflow(
  File "D:\a\snakemake\snakemake\snakemake\api.py", line 594, in execute_workflow
    workflow.execute(
  File "D:\a\snakemake\snakemake\snakemake\workflow.py", line 1261, in execute
    raise e
  File "D:\a\snakemake\snakemake\snakemake\workflow.py", line 1257, in execute
    success = self.scheduler.schedule()
              ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\snakemake\snakemake\snakemake\scheduler.py", line 275, in schedule
    run = self.job_selector(needrun)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\snakemake\snakemake\snakemake\scheduler.py", line 478, in job_selector
    return self._job_selector(jobs)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\a\snakemake\snakemake\snakemake\scheduler.py", line 614, in job_selector_ilp
    self._solve_ilp(prob)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\wrapt_timeout_decorator\wrapt_timeout_decorator.py", line 229, in wrapper
    return wrapped_with_timeout(wrap_helper)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\wrapt_timeout_decorator\wrapt_timeout_decorator.py", line 238, in wrapped_with_timeout
    return wrapped_with_timeout_process(wrap_helper)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\wrapt_timeout_decorator\wrapt_timeout_decorator.py", line 252, in wrapped_with_timeout_process
    return timeout_wrapper()
           ^^^^^^^^^^^^^^^^^
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\wrapt_timeout_decorator\wrap_function_multiprocess.py", line 48, in __call__
    self.__process.start()
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\multiprocess\process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\multiprocess\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\multiprocess\context.py", line 337, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\multiprocess\popen_spawn_win32.py", line 95, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\multiprocess\reduction.py", line 63, in dump
    ForkingPickler(file, protocol, *args, **kwds).dump(obj)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 420, in dump
    StockPickler.dump(self, obj)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 482, in dump
    self.save(obj)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 598, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 712, in save_reduce
    save(state)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 555, in save
    f(self, obj)  # Call unbound method with explicit self
    ^^^^^^^^^^^^
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 1217, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 987, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 1011, in _batch_setitems
    save(v)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 555, in save
    f(self, obj)  # Call unbound method with explicit self
    ^^^^^^^^^^^^
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 902, in save_tuple
    save(element)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 598, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 712, in save_reduce
    save(state)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 555, in save
    f(self, obj)  # Call unbound method with explicit self
    ^^^^^^^^^^^^
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 1217, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 987, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 1011, in _batch_setitems
    save(v)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 555, in save
    f(self, obj)  # Call unbound method with explicit self
    ^^^^^^^^^^^^
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 1473, in save_instancemethod0
    pickler.save_reduce(MethodType, (obj.__func__, obj.__self__), obj=obj)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 687, in save_reduce
    save(args)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 555, in save
    f(self, obj)  # Call unbound method with explicit self
    ^^^^^^^^^^^^
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 902, in save_tuple
    save(element)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 598, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 712, in save_reduce
    save(state)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 555, in save
    f(self, obj)  # Call unbound method with explicit self
    ^^^^^^^^^^^^
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 1217, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 987, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 1011, in _batch_setitems
    save(v)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 598, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 712, in save_reduce
    save(state)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 555, in save
    f(self, obj)  # Call unbound method with explicit self
    ^^^^^^^^^^^^
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 1217, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 987, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 1011, in _batch_setitems
    save(v)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 598, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 712, in save_reduce
    save(state)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 555, in save
    f(self, obj)  # Call unbound method with explicit self
    ^^^^^^^^^^^^
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 1217, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 987, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 1011, in _batch_setitems
    save(v)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 598, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 712, in save_reduce
    save(state)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 555, in save
    f(self, obj)  # Call unbound method with explicit self
    ^^^^^^^^^^^^
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 1217, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 987, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 1011, in _batch_setitems
    save(v)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 598, in save
    self.save_reduce(obj=obj, *rv)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 712, in save_reduce
    save(state)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 555, in save
    f(self, obj)  # Call unbound method with explicit self
    ^^^^^^^^^^^^
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 1217, in save_module_dict
    StockPickler.save_dict(pickler, obj)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 987, in save_dict
    self._batch_setitems(obj.items())
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 1011, in _batch_setitems
    save(v)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)
  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 573, in save
    rv = reduce(self.proto)
         ^^^^^^^^^^^^^^^^^^
  File "src\\datrie.pyx", line 664, in datrie.Trie.__reduce__
  File "src\\datrie.pyx", line 665, in datrie.Trie.__reduce__
  File "src\\datrie.pyx", line 721, in datrie.Trie.write
AttributeError: Can't get local object 'eval_resource_expression.<locals>.callable'

Traceback (most recent call last):

  File "D:\a\snakemake\snakemake\tests\common.py", line 377, in run
    dag_api.execute_workflow(

  File "D:\a\snakemake\snakemake\snakemake\api.py", line 594, in execute_workflow
    workflow.execute(

  File "D:\a\snakemake\snakemake\snakemake\workflow.py", line 1261, in execute
    raise e

  File "D:\a\snakemake\snakemake\snakemake\workflow.py", line 1257, in execute
    success = self.scheduler.schedule()
              ^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\a\snakemake\snakemake\snakemake\scheduler.py", line 275, in schedule
    run = self.job_selector(needrun)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\a\snakemake\snakemake\snakemake\scheduler.py", line 478, in job_selector
    return self._job_selector(jobs)
           ^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\a\snakemake\snakemake\snakemake\scheduler.py", line 614, in job_selector_ilp
    self._solve_ilp(prob)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\wrapt_timeout_decorator\wrapt_timeout_decorator.py", line 229, in wrapper
    return wrapped_with_timeout(wrap_helper)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\wrapt_timeout_decorator\wrapt_timeout_decorator.py", line 238, in wrapped_with_timeout
    return wrapped_with_timeout_process(wrap_helper)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\wrapt_timeout_decorator\wrapt_timeout_decorator.py", line 252, in wrapped_with_timeout_process
    return timeout_wrapper()
           ^^^^^^^^^^^^^^^^^

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\wrapt_timeout_decorator\wrap_function_multiprocess.py", line 48, in __call__
    self.__process.start()

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\multiprocess\process.py", line 121, in start
    self._popen = self._Popen(self)
                  ^^^^^^^^^^^^^^^^^

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\multiprocess\context.py", line 224, in _Popen
    return _default_context.get_context().Process._Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\multiprocess\context.py", line 337, in _Popen
    return Popen(process_obj)
           ^^^^^^^^^^^^^^^^^^

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\multiprocess\popen_spawn_win32.py", line 95, in __init__
    reduction.dump(process_obj, to_child)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\multiprocess\reduction.py", line 63, in dump
    ForkingPickler(file, protocol, *args, **kwds).dump(obj)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 420, in dump
    StockPickler.dump(self, obj)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 482, in dump
    self.save(obj)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 598, in save
    self.save_reduce(obj=obj, *rv)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 712, in save_reduce
    save(state)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 555, in save
    f(self, obj)  # Call unbound method with explicit self
    ^^^^^^^^^^^^

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 1217, in save_module_dict
    StockPickler.save_dict(pickler, obj)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 987, in save_dict
    self._batch_setitems(obj.items())

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 1011, in _batch_setitems
    save(v)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 555, in save
    f(self, obj)  # Call unbound method with explicit self
    ^^^^^^^^^^^^

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 902, in save_tuple
    save(element)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 598, in save
    self.save_reduce(obj=obj, *rv)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 712, in save_reduce
    save(state)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 555, in save
    f(self, obj)  # Call unbound method with explicit self
    ^^^^^^^^^^^^

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 1217, in save_module_dict
    StockPickler.save_dict(pickler, obj)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 987, in save_dict
    self._batch_setitems(obj.items())

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 1011, in _batch_setitems
    save(v)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 555, in save
    f(self, obj)  # Call unbound method with explicit self
    ^^^^^^^^^^^^

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 1473, in save_instancemethod0
    pickler.save_reduce(MethodType, (obj.__func__, obj.__self__), obj=obj)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 687, in save_reduce
    save(args)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 555, in save
    f(self, obj)  # Call unbound method with explicit self
    ^^^^^^^^^^^^

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 902, in save_tuple
    save(element)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 598, in save
    self.save_reduce(obj=obj, *rv)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 712, in save_reduce
    save(state)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 555, in save
    f(self, obj)  # Call unbound method with explicit self
    ^^^^^^^^^^^^

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 1217, in save_module_dict
    StockPickler.save_dict(pickler, obj)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 987, in save_dict
    self._batch_setitems(obj.items())

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 1011, in _batch_setitems
    save(v)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 598, in save
    self.save_reduce(obj=obj, *rv)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 712, in save_reduce
    save(state)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 555, in save
    f(self, obj)  # Call unbound method with explicit self
    ^^^^^^^^^^^^

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 1217, in save_module_dict
    StockPickler.save_dict(pickler, obj)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 987, in save_dict
    self._batch_setitems(obj.items())

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 1011, in _batch_setitems
    save(v)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 598, in save
    self.save_reduce(obj=obj, *rv)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 712, in save_reduce
    save(state)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 555, in save
    f(self, obj)  # Call unbound method with explicit self
    ^^^^^^^^^^^^

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 1217, in save_module_dict
    StockPickler.save_dict(pickler, obj)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 987, in save_dict
    self._batch_setitems(obj.items())

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 1011, in _batch_setitems
    save(v)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 598, in save
    self.save_reduce(obj=obj, *rv)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 712, in save_reduce
    save(state)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 555, in save
    f(self, obj)  # Call unbound method with explicit self
    ^^^^^^^^^^^^

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 1217, in save_module_dict
    StockPickler.save_dict(pickler, obj)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 987, in save_dict
    self._batch_setitems(obj.items())

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 1011, in _batch_setitems
    save(v)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 598, in save
    self.save_reduce(obj=obj, *rv)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 712, in save_reduce
    save(state)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 555, in save
    f(self, obj)  # Call unbound method with explicit self
    ^^^^^^^^^^^^

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 1217, in save_module_dict
    StockPickler.save_dict(pickler, obj)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 987, in save_dict
    self._batch_setitems(obj.items())

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 1011, in _batch_setitems
    save(v)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 414, in save
    StockPickler.save(self, obj, save_persistent_id)

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\pickle.py", line 573, in save
    rv = reduce(self.proto)
         ^^^^^^^^^^^^^^^^^^

  File "src\\datrie.pyx", line 664, in datrie.Trie.__reduce__

  File "src\\datrie.pyx", line 665, in datrie.Trie.__reduce__

  File "src\\datrie.pyx", line 721, in datrie.Trie.write

AttributeError: Can't get local object 'eval_resource_expression.<locals>.callable'

-------------------------- Captured stderr teardown ---------------------------
Traceback (most recent call last):

  File "<string>", line 1, in <module>

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\multiprocess\spawn.py", line 122, in spawn_main

    exitcode = _main(fd, parent_sentinel)

               ^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\multiprocess\spawn.py", line 132, in _main

    self = reduction.pickle.load(from_parent)

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 289, in load

    return Unpickler(file, ignore=ignore, **kwds).load()

           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\Users\runneradmin\micromamba\envs\snakemake\Lib\site-packages\dill\_dill.py", line 444, in load

    obj = StockUnpickler.load(self)

          ^^^^^^^^^^^^^^^^^^^^^^^^^

EOFError: Ran out of input
```

The same code runs fine on linus.
Any idea of what might be causing it?

* **Please tell us about your environment:**

- Version of wrapt_timeout_decorator : 1.5.1
- Python Version : 3.11
- OS, OS Version : Windows

**Comment by bitranox** [comment]
dill can not unpickle the object. You might try "pickle" instead of "dill", or narrow down the scope of the wrapped code, in order to see which part cant be pickled. If You find out which part cant be pickled by dill, You might report to the dill maintainers.
yours sincerely
Robert

**Comment by fgvieira** [comment]
But why only in Windows?
If it was a pickling issue, wouldn't it also be present on Linux?

**Comment by bitranox** [comment]
You can use the on-board tools of dill to identify unpickable objects : 
https://github.com/bitranox/wrapt_timeout_decorator?tab=readme-ov-file#detect-pickle-errors

If You want to use `pickle` instead of `dill`, You would need to fork the project and simply replace `dill` with `pickle` - but I doubt that `pickle` would work better then `dill`.
Best chance is to identify the object which cant be pickled with `dill` and report it to the `dill` maintainers.
